### ISSUE TITLE
Pins used on MKR 485 shield when using this library?

### ISSUE THREAD

**Issue by simonvanderveldt** [arduino-libraries/ArduinoDMX#2]
Hi!

I've got a small question about this library, hope that's OK. Since this library uses the RS485 library it seems like it defaults to using pin 1 for TX, see
https://github.com/arduino-libraries/ArduinoRS485/blob/f840235655bba5537b0d2cfb60405dabab477c62/src/RS485.h#L28

But the TX pin on the MKR 485 shield is pin 14 (see the schematic [here](https://content.arduino.cc/assets/MKR485ShieldV3.0_sch.pdf)). Does this mean that when using this library with the MKR 485 shield I'd have to configure the TX pin to be pin 14?

The schematic for the MKR 485 also shows pin 6 and 7 to be used, but I don't see any references to them in either the RS485 library nor this DMX library. Are they not actually necessary/used at all?

**Comment by 2788west** [comment]
@simonvanderveldt I'm trying to use this library with the MKR 485 shield and its not working at all, so I'm suspecting a similar issue. Were you able to resolve this?

**Comment by simonvanderveldt** [comment]
@2788west I don't use it anymore, only thing I could still find was this from my notes
```
// Pins used by MKR 485 Shield
// https://forum.arduino.cc/index.php?topic=618760.0
// A5 RE (receiver output enable)
// A6 DE (drive output enable)
// D13 Serial RX (not used :? in the RS485 library?)
// D14 Serial TX
```
```
Stack the MKR Zero and the shields together. Switch 3 on the MKR 485 should be set to ON, the other switches to OFF. The connections between the MKR 485 shield and the DMX302 are as follows:

    GND <=> GND
    Y <=> D+
    Z <=> D-

Don't forget to terminate the RS485 bus on the DMX302 using a 120 Ohm resistor.
```
(I was connecting to a DMX302).

I didn't make any changes to the library, was using version 1.0.1, and it worked fine.
That's all I can give you, hope it helps :)

**Comment by 2788west** [comment]
@simonvanderveldt Very helpful, thank you!

**Comment by aentinger** [comment]
Closing, since solved.
